<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ravi-Aspire-5755" ignored="1" name="Personal loan" tests="5" failures="1" timestamp="11 Feb 2018 14:54:37 GMT" time="0.115" errors="0">
  <testcase name="Demo" time="0.027" classname="testNGFiles.day1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at testNGFiles.day1.Demo(day1.java:22)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase name="ploan" time="0.002" classname="testNGFiles.day2"/>
  <testcase name="LoginAPIHomeLoan" time="0.005" classname="testNGFiles.day4"/>
  <testcase name="MobileLoginHomeLoan" time="0.005" classname="testNGFiles.day4"/>
  <testcase name="WebloginHomeLoan" time="0.01" classname="testNGFiles.day4"/>
  <testcase name="SecondTest" time="0.0" classname="testNGFiles.day1">
    <ignored/>
  </testcase> <!-- SecondTest -->
</testsuite> <!-- Personal loan -->
